[package]
name = "hello-world"
version = "0.1.0"
authors = ["AaronStGeorge <aaronstgeorge@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }